import type { NextPage } from "next";
import Head from "next/head";
import NextLink from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    if (localStorage.getItem("player") !== null) {
      router.push("/game");
    }
  }, []);

  return (
    <div>
      <Head>
        <title>crawleRPG</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        Hello World! Create your character here!{" "}
        <NextLink href='/create' passHref>
          Create
        </NextLink>
      </main>
    </div>
  );
};

export default Home;
